version: "3"

services:
  server:
    build: ./
    container_name: dashboard_worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DATA_UPLOAD: kafka
      SERVER_NAME: OliversMBP
      KAFKA_TOPIC: test
      KAFKA_URL: kafka2.cfei.dk:9093
