version: "3"

services:
  server:
    image: omvk97/dashboard-server:1.0.3
    container_name: dashboard-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DASHBOARDS_SERVER_NAME: OliversMBP
      DASHBOARDS_KAFKA_URL: 64.227.69.203:9093
      DASHBOARDS_KERBEROS_PUBLIC_URL: 64.227.69.203
      DASHBOARDS_KERBEROS_REALM: KAFKA.SECURE
      DASHBOARDS_KERBEROS_API_URL: http://64.227.69.203:6000/get-keytab
      DASHBOARDS_KERBEROS_API_SERVICE_USERNAME: dashboardserver/64.227.67.167
      DASHBOARDS_KERBEROS_API_SERVICE_PASSWORD: dashboardServerPassword
      DASHBOARDS_BROKER_KERBEROS_SERVICE_NAME: kafka
