version: "3"

services:
  server:
    image: omvk97/dashboard-server
    container_name: dashboard-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DASHBOARDS_SERVER_NAME: OliversMBP
      DASHBOARDS_KAFKA_URL: 134.122.57.152:9093
      DASHBOARDS_KERBEROS_PUBLIC_URL: 134.122.57.152
      DASHBOARDS_KERBEROS_REALM: KAFKA.SECURE
      DASHBOARDS_KERBEROS_API_URL: http://134.122.57.152:6000/get-keytab
      DASHBOARDS_KERBEROS_API_SERVICE_USERNAME: dashboardserver/134.122.57.152
      DASHBOARDS_KERBEROS_API_SERVICE_PASSWORD: dashboardServerPassword
      DASHBOARDS_BROKER_KERBEROS_SERVICE_NAME: kafka
